title: Kousher Alam -- Full Stack Developer
email: kousheralampranto@gmail.com
description: >- # this means to ignore newlines until next property
  I love to code, have experience with large architecture design 
  for front end application, web development and mobile application development.  
  I believe code must be maintainable, scaleable and  readable in 5 
  second cookie rule And I do not write nested ternary code. 

sub_description: I love to use build and automated tools such as webpack, gulp, sometimes simple node-script do the job. And also  bitbuket pipeline.


baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kousheralam.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Url And Links 
twitter_username: jekyllrb
github_username:  jekyll

# Description
skill_description: My Skill Description 
experience_description: My Experience Description
workprocess_description: My work process description
thinking_description: My thinking description
hobby_description: My Hobby description 
contact_description: My Contact Description
contact_hire_description: My contact hire description

# Journey 
skills: 
  - 
    title: Front End Development
    type: expert 
    description: I have over 2 year of experience working with angular react and vue. I have in dept knowledge in rxjs, ngrx,redux,vux, axios and other library. I Have in dept knowledge in HTML5, CSS3, Diffeent templating laguage such as pug, markdown, jekyll, and I also have experience in different css architecture such as triangle css, smacss architecture. 
  - 
    title: NodeJS, express and nestjs
    type: expert 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: PHP Development
    type: expert 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Database Programming
    type: expert 
    description: SQL, PostgreSQ, NoSql, Mongodb, In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Data Visualization and Charting
    type: intermediate 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Python, Flask, Django
    type: expert 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Wordpress Development
    type: expert 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Mobile App Development
    type: intermediate 
    description: Flutter, Nativescript, Ionic, In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Continuous Integration
    type: basic 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Docker
    type: basic 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 
  - 
    title: Electron
    type: basic 
    description: In April 2013 I start my development journey, First i learn how to develop a web page with dreamwaver then i strt learning HTML and CSS. 


# My Hobby
hobbies: 
  - 
    title: Cycling
    description: I love to ride cycle. 

# Articles or My thought Publish on Platform 
articles: 
  - 
    title: Main Key Of Software Development
    link: https://getbootstrap.com/docs/4.3/getting-started/download/
    description: In this Topic I try to clearify the base misconception about software engineering
  - 
    title: Angular and how i made my life easier
    link: https://getbootstrap.com/docs/4.3/getting-started/download/
    description: In this Topic I try to clearify the base misconception about software engineering


# Work Process 
workprocess: 
  - 
    title: My Strategy for developing a project from ground to production
    description: Some Description about the process 
  - 
    title: My approch to a probelm
    description: Some Description about the process 
  - 
    title: My approch to a challenge
    description: Some Description about the process 

# Assests description 
my_image: images/me.jpg

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: compressed

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
