title: Front End Developer
email: kousheralampranto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
analytics: UA-111712473-1
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kousheralam.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: kousehralam
github_username:  kousheralam


# Build settings
markdown: kramdown
paginate: 5
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
  style: compressed
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
