url: "https://kousheralam.tech" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kousher Alam" # the name of your site, e.g. ACME Corp.

collections:
  blog_category : 
    output: true
    permalink: /blog/by-category/:path/
  portfolio : 
    output: true
    permalink: /portfolio/:path/
  portfolio_category : 
    output: true
    permalink: /portfolio/by-category/:path/
  demo : 
    output: true
    permalink: /demo/:path/
  demo_category : 
    output: true
    permalink: /demo/by-category/:path/

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


social_links:
  facebook: https://facebook.com/MdKousherAlam
  twitter: https://twitter.com/Kousheralam1
  linkedin: https://www.linkedin.com/in/kousheralam/
  github: https://github.com/kousherAlam
  stackoverflow: https://stackoverflow.com/users/7448841/kousher-alam-pranto
  npm: https://www.npmjs.com/~kousher

defaults:
  - scope:
      path: "_portfolio"
      type: "portfolio"
    values:
      layout: portfolio
      permalink: /portfolio/:title:output_ext
  - scope:
      path: "_portfolio_category"
      type: "portfolio"
    values:
      layout: portfolio-category
      permalink: /portfolio/:title:output_ext
  - scope:
      path: "_demo"
      type: "demo"
    values:
      layout: demo
      permalink: /demo/:title:output_ext
  - scope:
      path: "_demo_category"
      type: "demo"
    values:
      layout: demo-category
      permalink: /demo/:title:output_ext
  - scope:
      path: "_posts"
    values:
      layout: blog
      type: post
      permalink: /blog/:categories/:year/:month/:day/:title:output_ext
  - scope:
      path: "_blog_category"
      type: "blog-category"
    values:
      layout: blog-category
      permalink: /blog/:categories/:title:output_ext

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-get-json
  - jekyll-paginate
  # - jekyll-paginate
