title: My Blogs
email: kousheralampranto@gmail.com
description: >- # this means to ignore newlines until next property
  I love to code, have experience with large architecture design 
  for front end application, web development and mobile application development.  
  I believe code must be maintainable, scaleable and  readable in 5 
  second cookie rule And I do not write nested ternary code. 

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kousheralam.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Url And Links
twitter_username: jekyllrb
github_username: jekyll
linkedin: https://www.linkedin.com/in/kousheralam/
cvlink: https://drive.google.com/file/d/1EuWTBF1UwEP-cf3I92zeqhEhdGxLhATX/view?usp=sharing


# Assests description
my_image: images/me.jpg

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: compressed

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
