url: "https://kousheralam.tech" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kousher Alam" # the name of your site, e.g. ACME Corp.

collections:
  blog_category : 
    output: true


# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


social_links:
  - image: twitter.svg
    link: https://twitter.com/Kousheralam1
    alt: Twitter
  - image: linkedin.svg
    link: https://www.linkedin.com/in/kousheralam/
    alt: LinkedIn
  - image: github.svg
    link: https://github.com/kousherAlam
    alt: Github
  - image: stackoverflow.svg
    link: https://stackoverflow.com/users/7448841/kousher-alam-pranto
    alt: StackOverlfow
  - image: npm.svg
    link: https://www.npmjs.com/~kousher
    alt: npm - Node Package Manager

defaults:
  - scope:
      path: "_porfolios"
      type: "porfolios"
    values:
      layout: portfolio
      permalink: /portfolio/:title:output_ext
  - scope:
      path: "_posts"
      type: "blog"
    values:
      layout: blog
      permalink: /blog/:categories/:year/:month/:day/:title:output_ext
  - scope:
      path: "_blog_category"
      type: "blog-category"
    values:
      layout: blog-category
      permalink: /blog/:categories/:title:output_ext

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-get-json
  - jekyll-paginate
  # - jekyll-paginate
