title: Kousher Alam -- Full Stack Developer
email: kousheralampranto@gmail.com
description: >- # this means to ignore newlines until next property 

  I love to code, have experience with large architecture design 
  for front end application, web development and mobile application development.  
  I believe code must be maintainable, scaleable and  readable in 5 
  second cookie rule And I do not write nested ternary code. 

sub_description: >-
  I'm also addicted to automated tools such as webpack, gulp, 
  sometimes simple node-script or python script. 
  so i spend some of my time tweaking and updating automation tools. 
  I love automation scripts and tools very much as they simplify boaring task, 
  and create time by doing repetative task. 


baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kousheralam.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Url And Links 
twitter_username: jekyllrb
github_username:  jekyll


experiecnes: 
  - 
    company_name: Nybsys 
    website: https://nybsys.com 
    start: July 15 2017
    end: Currently Working Here
    position: Web Developer
    description: >-
      Nybsys is a multinational company they are mainly focus on iot and machine
      learning. My responsibility here is develop new optimized client application for their existing
      software and iot device control panel. I also develop website for them if necessary.
  - 
    company_name: AtiqeIT
    website: https://www.facebook.com/atiqueit/
    start: March 2017
    end: June 2017
    position: PHP Programmer
    description: >-
      A Web development base company my main work area was, develop new feature for
      their client use php - codeigniter framework.
  - 
    company_name: ugdm.gov.edu
    website: https://nybsys.com 
    start: 2016
    end: 2017
    position: Web Developer
    description: >-
      A School management system. Mainly for managing their student and teacher data.
      Work as a team lead. I Manage the team code complex part of the application.

workprocess_description: >- 
  Everyone has their own workprocess, somethimes we follow industry 
  stundard workflow and guideline to made our work effectively and efficiently. 
  In this section how i shared my workflow, i hope it will give you very good idea. 

thinking_description: >- 
  Sometimes i love to share my knowledge with others, it's enable me 
  to share my prospective with others and also justify my idea on public.

hobby_description: >- 
  In my free time i spend my time on my hobby, it 
  give me courage and remove my all failure and Frustration. 

contact_description: >- 
  If you want to tell / ask me something you can do so by the form. 

contact_hire_description: >-
  Do want to hire me ?? It's very easy, Just send message or hire on upwork. 

# My Skills List and Their Details 
skills: 
  - 
    id: front_end_development
    title: Front End Development
    image: ''
    description: >- 
      I have over 2 year of experience working with angular react and vue. 
      I have in dept knowledge in rxjs, ngrx,redux,vux, axios and other library. 
      I Have in dept knowledge in HTML5, CSS3, Diffeent templating laguage such as pug, markdown, 
      jekyll, and I also have experience in different css architecture such as triangle css, smacss
       architecture. I love to write my javascript code in typescript 
       as it give me complete type support and make our life more easire by detecting 
       problem before hppening and made debugging easier.
    projects: 
      - 
        project_name: CellMon
        description: Some description about angular
        my_responsibility: This was my responsiblity
        team: true
        technology: 
          - 
            skill_name: "Angular"
            me: true
      - 
        project_name: CDAS
        description: Some description about angular
        my_responsibility: This was my responsiblity
        team: true
        technology: 
          - 
            skill_name: "Angular"
      - 
        project_name: DrinkWell
        description: Some description about angular
        my_responsibility: This was my responsiblity
        team: true
        technology: 
          - 
            skill_name: "Angular"
            me: true
      - 
        project_name: IG100 Dashboard
        description: Some description about angular
        my_responsibility: This was my responsiblity
        team: true
        technology: 
          - 
            skill_name: "Angular"
            me: true
        


  - 
    id: nodejs
    title: Nodejs
    image: ''
    description: >- 
      Nodejs is very lightweight single threaded server side framework for javascript. 
      I have expertise knowledge in nodejs automation tools development, express and nest js. 
    projects: 



  - 
    id: php_development
    title: PHP Development
    image: ''
    description: >-
      I bulild 5-6 solution using php, I used php codeigniter, 
      laravel to build those solution, they are, HR-Management System, 
      Directory Management System, Employee management System, School Management System , etc..
    projects: 


  - 
    id: database_programming
    title: Database Programming
    image: ''
    description: >- 
      Modern day's programming without database is unbeliveable, 
      I have extertise in SQL, Postgresql, and In Mongodb. 
      I can easily made dicision about which kind of database will be use for out solution.  
    projects: 


  - 
    id: data_sualization
    title: Data Visualization
    description: >- 
      In modern day solution, without at a glance visulalization is impossible, 
      I have experiecne building different kind of visualization. 
      Which make our application more attractive and easier to understand. 
    projects: 


  - 
    id: python_flask_django
    title: Python, Flask, Django
    image: ''
    description: >- 
      Python is a very suffisticated tool to develop solution quickly and reliably. 
      There are thousand of pacakages for helping us quick development. 
    projects: 


  - 
    id: wordpress_development
    title: Wordpress
    image: ''
    description: >- 
      In modern day, there 25% of website build on wordpress, 
      I have experience in wordpress customization, theme and plugin development. 
    projects: 


  - 
    id: mobile_app_development
    title: Mobile App     
    image: ''
    description: >- 
      I Build Mobile application very ofthen, sometimes i use ionic, 
      somtimes nativescript, but recently i'm using flutter, With flutter 
      i can develop application very quickly , it is native and very fast compare 
      to other compititor of it's. And It's also make cross platform application which is win win.
    projects: 

      
  - 
    id: desktop_app_dev
    title: Desktop Application
    image: ''
    description: >- 
      To build cross platform desktop application i use electron, 
      it allow me to use html, css as ui language and javascript as programming language, 
      it easy, fast and relaiable.   
    projects: 


  - 
    id: continuous_integration
    title: Continuous Integration
    image: ''
    description: >- 
      Continuous integration is the backbone of very large scale application. 
      cause in very large scale app if . 
    projects: 

      
  - 
    id: dockers
    title: Docker
    image: ''
    description: >- 
      Docker is a very nice technology to work with. It help us to solve, 
      i't work on my pc problem and it is very fast than virtual matchine.  
    projects: 


# My Hobby
hobbies: 
  - 
    title: Cycle riding
    description: >- 
      I love to ride cycle. 
  - 
    title: Book Reading
    description: >- 
      I love to read book, my favorite write is Arthur Conan Doyle, 
      Humayn Ahmed, And I love poetry of Kazi Nozrul Islam and Robindronath. 
  - 
    title: Travelling
    description: >-
      Travelling in different place. 


# Articles or My thought Publish on Platform 
articles: 
  - 
    title: Main Key Of Software Development
    link: https://getbootstrap.com/docs/4.3/getting-started/download/
    description: In this Topic I try to clearify the base misconception about software engineering


linkedin: "https://www.linkedin.com/in/kousheralam/"
cvlink: "https://drive.google.com/file/d/1EuWTBF1UwEP-cf3I92zeqhEhdGxLhATX/view?usp=sharing" 


# Assests description 
my_image: images/me.jpg

# Build settings
markdown: kramdown
sass:
  sass_dir: css
  style: compressed

plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
